name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup glcoud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - run: gsutil cp gs://pfy-continuous-deployment/last-successful-commit.txt ./pfy-start-commit.txt

    - run: npm ci
    - run: npm run affected:lint -- --parallel --base=`cat pfy-start-commit.txt` --head=HEAD
    - run: npm run affected:build -- --parallel --prod --base=`cat pfy-start-commit.txt` --head=HEAD
    - run: npm run affected:test -- --parallel --base=`cat pfy-start-commit.txt` --head=HEAD
      env:
        NODE_ENV: CI

    - run: npm run affected -- --target=deploy --parallel --base=`cat pfy-start-commit.txt` --head=HEAD

    - run: touch last-successful-commit.txt
    - run: echo ${{ github.event.after }} > last-successful-commit.txt
    - run: gsutil cp ./last-successful-commit.txt gs://pfy-continuous-deployment/last-successful-commit.txt
