name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run affected:lint -- --all
    - run: npm run affected:build -- --all --prod
    - run: npm run affected:test -- --all
      env:
        NODE_ENV: CI
