name: CI

on:
  push:
    branches: [ '*', '!master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: NPM cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: git fetch --no-tags --prune --depth=5 origin master
    - run: npm ci
    - run: npm run affected:lint -- --parallel --base=origin/master --head=HEAD
    - run: npm run affected:build -- --parallel --prod --base=origin/master --head=HEAD
    - run: npm run affected:test -- --parallel --base=origin/master --head=HEAD
      env:
        NODE_ENV: CI
